#!/bin/bash
# QUICKSTART.sh - Immediate deployment guide

echo "IoT Platform Installer - Quick Start"
echo "====================================="
echo ""
echo "System Status: ✅ ALL FILES COMPLETE (50+ files)"
echo ""
echo "Next Steps:"
echo ""
echo "1. Make executable:"
echo "   chmod +x install.sh"
echo ""
echo "2. Preview installation (recommended):"
echo "   sudo ./install.sh --dry-run"
echo ""
echo "3. Run installation:"
echo "   sudo ./install.sh"
echo ""
echo "What you'll be asked:"
echo "  - VPS IP (auto-detected)"
echo "  - Username (default: iotadmin)"
echo "  - SSH port (default: 5259)"
echo "  - Domain (optional)"
echo "  - All passwords auto-generated"
echo ""
echo "Installation time: ~3h 15m"
echo ""
echo "Critical pauses (manual validation required):"
echo "  - Phase 1: New user validation"
echo "  - Phase 5: SSH port test"
echo ""
echo "After installation:"
echo "  1. Backup: ~/.iot-platform/.secrets"
echo "  2. Test: curl http://localhost/health"
echo "  3. Login: curl -X POST http://localhost/api/v1/auth/login/admin \\"
echo "           -H 'Content-Type: application/json' \\"
echo "           -d '{\"email\":\"admin@iot-platform.com\",\"password\":\"admin123\"}'"
echo ""
echo "Documentation:"
echo "  - README.md - Full usage guide"
echo "  - COMPLETION_CHECKLIST.md - Verification steps"
echo ""
echo "Ready to install? Run: sudo ./install.sh"
