# /// script
# requires-python = ">=3.10"
# description = "Provisioning tool: reads server .secrets, computes keys, generates config.json for ESP32."
# ///
"""
ESP32 Device Provisioning Tool.

Reads the server's .secrets file (generated by install.sh), extracts all
necessary credentials, computes the server_key, and generates a complete
config.json ready to upload to the ESP32.

The only manual input required is the WiFi SSID and password. All other
fields are auto-populated from .secrets. If any field is missing from
.secrets, the script falls back to interactive prompts for those fields.

WiFi can be left empty if it will be configured later via the web flasher.

Usage:
    uv run compute_server_key.py
"""

import hashlib
import json
import socket
import sys
from pathlib import Path

SECRETS_PATH = Path.home() / ".iot-platform" / ".secrets"

THRESHOLDS_DEFAULT: dict = {
    "temp_high": 35.0,
    "temp_low": 18.0,
    "humidity_high": 80,
    "noise_high_v": 2.5,
    "noise_medium_v": 2.0,
}


def compute_server_key(secret_key: str) -> str:
    """Derive server_key hex from the server's SECRET_KEY."""
    raw = (secret_key + "|puzzle_v1").encode("utf-8")
    return hashlib.sha256(raw).hexdigest()


def parse_secrets(filepath: Path) -> dict[str, str]:
    """Parse KEY="value" lines from a .secrets file."""
    secrets: dict[str, str] = {}
    for line in filepath.read_text().splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if "=" in line:
            key, _, val = line.partition("=")
            secrets[key.strip()] = val.strip().strip('"').strip("'")
    return secrets


def detect_local_ip() -> str:
    """Best-effort detection of this machine's LAN IP."""
    try:
        s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        s.connect(("8.8.8.8", 80))
        ip = s.getsockname()[0]
        s.close()
        return ip
    except OSError:
        return ""


def prompt(label: str, default: str = "", validate_fn=None, required: bool = True) -> str:
    """Prompt for user input with optional validation and default value."""
    suffix = " [{}]: ".format(default) if default else ": "
    for attempt in range(3):
        value = input(label + suffix).strip()
        if not value and default:
            value = default
        if not value and not required:
            return ""
        if not value and required:
            print("  Campo requerido. Intenta de nuevo.")
            continue
        if validate_fn:
            err = validate_fn(value)
            if err:
                print("  {}. Intenta de nuevo.".format(err))
                continue
        return value
    print("  Demasiados intentos fallidos.")
    sys.exit(1)


def validate_hex64(val: str) -> str | None:
    """Validate a 64-character hex string."""
    if len(val) != 64:
        return "Debe ser exactamente 64 caracteres hex (tienes {})".format(len(val))
    try:
        bytes.fromhex(val)
    except ValueError:
        return "Caracteres hex invalidos"
    return None


def validate_int(val: str) -> str | None:
    """Validate a positive integer."""
    try:
        n = int(val)
        if n <= 0:
            return "Debe ser un entero positivo"
    except ValueError:
        return "No es un entero valido"
    return None


def validate_url(val: str) -> str | None:
    """Validate URL starts with http:// or https://."""
    if not val.startswith(("http://", "https://")):
        return "Debe empezar con http:// o https://"
    return None


def main() -> None:
    print()
    print("=" * 55)
    print("  ESP32 Device Provisioning Tool")
    print("  Genera config.json para firmware MicroPython")
    print("=" * 55)
    print()

    # --- Step 1: Find and read .secrets ---
    secrets: dict[str, str] = {}
    secrets_path = SECRETS_PATH

    if secrets_path.exists():
        print("[AUTO] Leyendo {}".format(secrets_path))
        secrets = parse_secrets(secrets_path)
    else:
        print("[INFO] No se encontro {}".format(secrets_path))
        alt = input("Ruta al archivo .secrets (o Enter para modo manual): ").strip()
        if alt:
            alt_path = Path(alt).expanduser()
            if alt_path.exists():
                secrets = parse_secrets(alt_path)
                secrets_path = alt_path
                print("[AUTO] Leyendo {}".format(alt_path))
            else:
                print("[WARN] Archivo no encontrado, modo manual activado")
    print()

    # --- Step 2: Extract or prompt each field ---
    config: dict = {}

    # SECRET_KEY -> server_key_hex
    secret_key = secrets.get("SECRET_KEY", "")
    if secret_key:
        server_key_hex = compute_server_key(secret_key)
        print("[AUTO] SECRET_KEY encontrado, server_key_hex computado")
    else:
        print("[MANUAL] SECRET_KEY no encontrado en .secrets")
        secret_key = prompt("SECRET_KEY")
        server_key_hex = compute_server_key(secret_key)
    config["server_key_hex"] = server_key_hex

    # DEVICE_ENCRYPTION_KEY -> device_key_hex
    device_key = secrets.get("DEVICE_ENCRYPTION_KEY", "")
    if device_key:
        err = validate_hex64(device_key)
        if err:
            print("[WARN] DEVICE_ENCRYPTION_KEY invalido en .secrets: {}".format(err))
            device_key = ""
    if device_key:
        print("[AUTO] DEVICE_ENCRYPTION_KEY encontrado")
    else:
        device_key = prompt("device_key_hex (64 hex chars)", validate_fn=validate_hex64)
    config["device_key_hex"] = device_key

    # DEVICE_API_KEY -> api_key
    api_key = secrets.get("DEVICE_API_KEY", "")
    if api_key:
        print("[AUTO] DEVICE_API_KEY encontrado ({} chars)".format(len(api_key)))
    else:
        api_key = prompt("api_key")
    config["api_key"] = api_key

    # device_id (default 1, seeded device)
    config["device_id"] = 1
    print("[AUTO] device_id = 1 (dispositivo inicial)")

    # SERVER_URL
    server_url = secrets.get("SERVER_URL", "")
    if not server_url:
        local_ip = detect_local_ip()
        default_url = "http://{}".format(local_ip) if local_ip else "http://192.168.1.100"
        server_url = prompt("Server URL", default=default_url, validate_fn=validate_url)
    else:
        print("[AUTO] SERVER_URL = {}".format(server_url))
    config["server_url"] = server_url

    # server_port
    config["server_port"] = 5000
    print("[AUTO] server_port = 5000")

    print()

    # --- Step 3: WiFi (optional, can be filled later in web flasher) ---
    print("WiFi (dejar ambos vacios si se configurara en el web flasher):")
    wifi_ssid = input("  WiFi SSID: ").strip()
    wifi_pass = ""
    if wifi_ssid:
        wifi_pass = input("  WiFi password: ").strip()
        if not wifi_pass:
            print("  SSID ingresado sin password, ambos son requeridos.")
            wifi_pass = input("  WiFi password: ").strip()
            if not wifi_pass:
                print("  Sin password. WiFi queda pendiente para el web flasher.")
                wifi_ssid = ""
    if not wifi_ssid:
        wifi_ssid = "REPLACE_WIFI_SSID"
        wifi_pass = "REPLACE_WIFI_PASS"
        print("  WiFi queda como placeholder (configurar en web flasher)")

    config["wifi_ssid"] = wifi_ssid
    config["wifi_pass"] = wifi_pass

    # --- Step 4: Optional fields with defaults ---
    config["read_interval_s"] = 30
    config["location"] = "Lab-01"
    config["thresholds"] = THRESHOLDS_DEFAULT

    # --- Step 5: Write config.json ---
    output_path = Path("config.json")
    with open(output_path, "w") as f:
        json.dump(config, f, indent=2)

    print()
    print("=" * 55)
    print("  config.json generado: {}".format(output_path.resolve()))
    print("=" * 55)
    print()
    print("  server_key_hex: {}...{}".format(server_key_hex[:12], server_key_hex[-8:]))
    print("  device_key_hex: {}...{}".format(device_key[:12], device_key[-8:]))
    print("  api_key:        {}...{}".format(api_key[:8], api_key[-4:]))
    print("  device_id:      {}".format(config["device_id"]))
    print("  server:         {}:{}".format(config["server_url"], config["server_port"]))
    wifi_status = "configurado" if not wifi_ssid.startswith("REPLACE") else "PENDIENTE (web flasher)"
    print("  wifi:           {}".format(wifi_status))
    print()


if __name__ == "__main__":
    main()
