# =============================================================================
# IoT Fire Prevention Platform - Environment Configuration
# Generated by installer
# =============================================================================

# MySQL Configuration
MYSQL_ROOT_PASSWORD={{MYSQL_ROOT_PASSWORD}}
MYSQL_DATABASE=fire_preventionf
MYSQL_USER=iot_user
MYSQL_PASSWORD={{MYSQL_PASSWORD}}
MYSQL_HOST=mysql
MYSQL_PORT=3306

# MongoDB Configuration (ACTIVE - Sensor Data)
MONGO_PASSWORD={{MONGO_PASSWORD}}
MONGO_HOST=mongodb
MONGO_PORT=27017
MONGO_USER=admin
MONGO_DATABASE=iot_sensors
MONGO_AUTH_SOURCE=admin

# Redis Configuration
REDIS_PASSWORD={{REDIS_PASSWORD}}
REDIS_HOST=redis
REDIS_PORT=6379

# FastAPI Configuration
SECRET_KEY={{SECRET_KEY}}
ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=60

# Application
APP_ENV=production
TZ=America/Mexico_City

# Logging
LOGS_DIR=/var/log/fastapi

# Database URL (constructed)
DATABASE_URL=mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}