# =============================================================================
# Plataforma IoT con Seguridad Integrada - Configuración de Entorno
# Generado por el instalador
# =============================================================================

# Configuración de MySQL
MYSQL_ROOT_PASSWORD={{MYSQL_ROOT_PASSWORD}}
MYSQL_DATABASE={{DB_NAME}}
MYSQL_USER=iot_user
MYSQL_PASSWORD={{MYSQL_PASSWORD}}
MYSQL_HOST=mysql
MYSQL_PORT=3306

# Configuración de MongoDB (ACTIVO - Datos de Sensores)
MONGO_IMAGE={{MONGO_IMAGE}}
MONGO_PASSWORD={{MONGO_PASSWORD}}
MONGO_HOST=mongodb
MONGO_PORT=27017
MONGO_USER=admin
MONGO_DATABASE=iot_sensors
MONGO_AUTH_SOURCE=admin

# Configuración de Redis
REDIS_PASSWORD={{REDIS_PASSWORD}}
REDIS_HOST=redis
REDIS_PORT=6379
REDIS_MEMORY={{REDIS_MEMORY}}

# Configuración de FastAPI
SECRET_KEY={{SECRET_KEY}}
ALGORITHM=HS256
ACCESS_TOKEN_EXPIRE_MINUTES=60

# Aplicación
APP_ENV=production
TZ={{TIMEZONE}}
RESOURCE_PROFILE={{RESOURCE_PROFILE}}
COMPACT_STORAGE={{COMPACT_STORAGE}}
SAFE_AUTOPURGE={{SAFE_AUTOPURGE}}
STORAGE_ALERTS={{STORAGE_ALERTS}}
STORAGE_PURGE_MODE={{STORAGE_PURGE_MODE}}
DATA_RETENTION_DAYS={{DATA_RETENTION_DAYS}}
STORAGE_TOTAL_MB={{STORAGE_TOTAL_MB}}
STORAGE_AVAILABLE_MB={{STORAGE_AVAILABLE_MB}}

# Registro de Logs
LOGS_DIR=/var/log/fastapi

# URL de Base de Datos (construida)
DATABASE_URL=mysql+pymysql://${MYSQL_USER}:${MYSQL_PASSWORD}@${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}

# Tuning de recursos aplicado por el instalador
MYSQL_INNODB_BUFFER_POOL={{MYSQL_INNODB_BUFFER_POOL}}
MYSQL_MAX_CONNECTIONS={{MYSQL_MAX_CONNECTIONS}}
MONGO_WIREDTIGER_CACHE={{MONGO_WIREDTIGER_CACHE}}
FASTAPI_WORKERS={{FASTAPI_WORKERS}}
