-- ============================================================================
-- IoT Fire Prevention Platform - MySQL Database Initialization
-- ============================================================================
-- This script creates the complete database schema (14 tables) and test data
-- Generated by IoT Platform Installer
-- ============================================================================

CREATE DATABASE IF NOT EXISTS {{DB_NAME}};
USE {{DB_NAME}};

-- ============================================================================
-- RBAC Tables (3 tables)
-- ============================================================================

-- Roles table
CREATE TABLE IF NOT EXISTS rol (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(50) UNIQUE NOT NULL,
    descripcion TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Permissions table
CREATE TABLE IF NOT EXISTS permission (
    id INT PRIMARY KEY AUTO_INCREMENT,
    name VARCHAR(100) UNIQUE NOT NULL,
    description TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Role-Permission junction table
CREATE TABLE IF NOT EXISTS rol_permiso (
    rol_id INT NOT NULL,
    permiso_id INT NOT NULL,
    PRIMARY KEY (rol_id, permiso_id),
    FOREIGN KEY (rol_id) REFERENCES rol(id) ON DELETE CASCADE,
    FOREIGN KEY (permiso_id) REFERENCES permission(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- Password Tables (4 separate tables with encryption keys)
-- ============================================================================

-- Admin passwords
CREATE TABLE IF NOT EXISTS pasadmin (
    id INT PRIMARY KEY AUTO_INCREMENT,
    hashed_password VARCHAR(255) NOT NULL,
    encryption_key BINARY(32)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- User passwords
CREATE TABLE IF NOT EXISTS pasusuario (
    id INT PRIMARY KEY AUTO_INCREMENT,
    hashed_password VARCHAR(255) NOT NULL,
    encryption_key BINARY(32)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Manager passwords
CREATE TABLE IF NOT EXISTS pasgerente (
    id INT PRIMARY KEY AUTO_INCREMENT,
    hashed_password VARCHAR(255) NOT NULL,
    encryption_key BINARY(32)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Device API keys
CREATE TABLE IF NOT EXISTS pasdispositivo (
    id INT PRIMARY KEY AUTO_INCREMENT,
    api_key VARCHAR(255) UNIQUE NOT NULL,
    encryption_key BINARY(32)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- Main Entity Tables (4 tables)
-- ============================================================================

-- Admins
CREATE TABLE IF NOT EXISTS admin (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    rol_id INT NOT NULL,
    pasadmin_id INT UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (rol_id) REFERENCES rol(id),
    FOREIGN KEY (pasadmin_id) REFERENCES pasadmin(id) ON DELETE CASCADE,
    INDEX idx_email (email),
    INDEX idx_rol (rol_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Users
CREATE TABLE IF NOT EXISTS usuario (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    rol_id INT NOT NULL,
    pasusuario_id INT UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (rol_id) REFERENCES rol(id),
    FOREIGN KEY (pasusuario_id) REFERENCES pasusuario(id) ON DELETE CASCADE,
    INDEX idx_email (email),
    INDEX idx_active (is_active),
    INDEX idx_rol (rol_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Managers
CREATE TABLE IF NOT EXISTS manager (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(100) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    admin_id INT NOT NULL,
    pasgerente_id INT UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (admin_id) REFERENCES admin(id) ON DELETE CASCADE,
    FOREIGN KEY (pasgerente_id) REFERENCES pasgerente(id) ON DELETE CASCADE,
    INDEX idx_email (email),
    INDEX idx_admin (admin_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Devices
CREATE TABLE IF NOT EXISTS device (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(100) NOT NULL,
    device_type ENUM('fire_sensor', 'smoke_detector', 'temperature_sensor', 'humidity_sensor', 'gas_detector', 'other') NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    admin_id INT NOT NULL,
    pasdispositivo_id INT UNIQUE NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_communication TIMESTAMP NULL,
    FOREIGN KEY (admin_id) REFERENCES admin(id) ON DELETE CASCADE,
    FOREIGN KEY (pasdispositivo_id) REFERENCES pasdispositivo(id) ON DELETE CASCADE,
    INDEX idx_admin (admin_id),
    INDEX idx_active (is_active),
    INDEX idx_type (device_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- Service & App Tables (2 tables)
-- ============================================================================

-- Services
CREATE TABLE IF NOT EXISTS service (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(100) NOT NULL,
    tipo VARCHAR(50) NOT NULL,
    descripcion TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Applications
CREATE TABLE IF NOT EXISTS app (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(100) NOT NULL,
    version VARCHAR(20) NOT NULL,
    admin_id INT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (admin_id) REFERENCES admin(id) ON DELETE CASCADE,
    INDEX idx_admin (admin_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- Many-to-Many Junction Tables (2 tables)
-- ============================================================================

-- Service-Device relationship
CREATE TABLE IF NOT EXISTS servicio_dispositivo (
    dispositivo_id INT NOT NULL,
    servicio_id INT NOT NULL,
    PRIMARY KEY (dispositivo_id, servicio_id),
    FOREIGN KEY (dispositivo_id) REFERENCES device(id) ON DELETE CASCADE,
    FOREIGN KEY (servicio_id) REFERENCES service(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Service-App relationship
CREATE TABLE IF NOT EXISTS servicio_app (
    servicio_id INT NOT NULL,
    app_id INT NOT NULL,
    PRIMARY KEY (servicio_id, app_id),
    FOREIGN KEY (servicio_id) REFERENCES service(id) ON DELETE CASCADE,
    FOREIGN KEY (app_id) REFERENCES app(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- ============================================================================
-- Initial Data - RBAC (Roles & Permissions)
-- ============================================================================

-- Insert roles
INSERT INTO rol (id, nombre, descripcion) VALUES
(1, 'superadmin', 'Super administrator with full access'),
(2, 'admin', 'Administrator with limited access'),
(3, 'user', 'Regular user with basic access'),
(4, 'manager', 'Manager with team oversight');

-- Insert permissions
INSERT INTO permission (id, name, description) VALUES
(1, 'read_users', 'Read user information'),
(2, 'write_users', 'Create and update users'),
(3, 'delete_users', 'Delete users'),
(4, 'read_devices', 'Read device information'),
(5, 'write_devices', 'Create and update devices'),
(6, 'delete_devices', 'Delete devices'),
(7, 'read_sensors', 'Read sensor information'),
(8, 'write_sensors', 'Create and update sensors'),
(9, 'read_readings', 'Read sensor readings'),
(10, 'write_readings', 'Submit sensor readings'),
(11, 'manage_roles', 'Manage roles and permissions'),
(12, 'view_logs', 'View system logs');

-- Assign permissions to roles
-- Superadmin: all permissions
INSERT INTO rol_permiso (rol_id, permiso_id) VALUES
(1, 1), (1, 2), (1, 3), (1, 4), (1, 5), (1, 6),
(1, 7), (1, 8), (1, 9), (1, 10), (1, 11), (1, 12);

-- Admin: most permissions except role management
INSERT INTO rol_permiso (rol_id, permiso_id) VALUES
(2, 1), (2, 2), (2, 4), (2, 5), (2, 6),
(2, 7), (2, 8), (2, 9), (2, 10), (2, 12);

-- User: read permissions only
INSERT INTO rol_permiso (rol_id, permiso_id) VALUES
(3, 1), (3, 4), (3, 7), (3, 9);

-- Manager: read/write for team, no delete
INSERT INTO rol_permiso (rol_id, permiso_id) VALUES
(4, 1), (4, 2), (4, 4), (4, 5), (4, 7), (4, 8), (4, 9), (4, 12);

-- ============================================================================
-- Test Data - Users and Devices
-- ============================================================================

-- Test Admin
-- Password: admin123 (bcrypt hashed)
INSERT INTO pasadmin (id, hashed_password) VALUES
(1, '{{ADMIN_PASSWORD_HASH}}');

INSERT INTO admin (id, nombre, email, rol_id, pasadmin_id) VALUES
(1, 'Administrador Principal', 'admin@iot-platform.com', 1, 1);

-- Test User
-- Password: user123 (bcrypt hashed)
INSERT INTO pasusuario (id, hashed_password) VALUES
(1, '{{USER_PASSWORD_HASH}}');

INSERT INTO usuario (id, nombre, email, is_active, rol_id, pasusuario_id) VALUES
(1, 'Usuario de Prueba', 'user@iot-platform.com', TRUE, 3, 1);

-- Test Manager
-- Password: manager123 (bcrypt hashed)
INSERT INTO pasgerente (id, hashed_password) VALUES
(1, '{{MANAGER_PASSWORD_HASH}}');

INSERT INTO manager (id, nombre, email, admin_id, pasgerente_id) VALUES
(1, 'Manager de Prueba', 'manager@iot-platform.com', 1, 1);

-- Test Device
INSERT INTO pasdispositivo (id, api_key) VALUES
(1, 'TEST_DEVICE_KEY_001_CHANGE_IN_PRODUCTION');

INSERT INTO device (id, nombre, device_type, is_active, admin_id, pasdispositivo_id) VALUES
(1, 'Dispositivo de Prueba', 'fire_sensor', TRUE, 1, 1);

-- Test Service
INSERT INTO service (id, nombre, tipo, descripcion) VALUES
(1, 'Fire Detection', 'monitoring', 'Fire detection and alert service');

-- Link device to service
INSERT INTO servicio_dispositivo (dispositivo_id, servicio_id) VALUES
(1, 1);

-- ============================================================================
-- End of initialization
-- ============================================================================
